---

- name: Add/remove users
  user:
    name: "{{ item.key }}"
    createhome: "{{ item.value.createhome|default(True) }}"
    shell: "{{ item.value.shell|default('/bin/bash') }}"
    generate_ssh_key: "{{ item.value.generate_ssh_key|default(False) }}"
    state: "{{ item.value.present|default('present') }}"
    password: "{{ item.value.password|default('') }}"
    update_password: "{{ item.value.update_password|default('always') }}"
    groups: "{{ item.value.groups|default('') }}"
  with_dict: "{{ users.users }}"

- name: Add user accounts to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ item.key }}
    owner: root
    group: root
    mode: "0440"
    validate: 'visudo -cf %s'
  with_dict: "{{ users.users }}"
  when: item.value.sudoers is defined and item.value.sudoers
  tags:
    - users-sudoers

- name: Remove empty or unmanaged sudoers files
  file:
    path: /etc/sudoers.d/{{ item.key }}
    state: absent
  with_dict: "{{ users.users }}"
  when: item.value.sudoers is not defined or not item.value.sudoers
  tags:
    - users-sudoers

- name: Fetch all public ssh keys from all nodes
  shell: cat {{ users.ssh.fetch_key }}
  register: users_ssh_keys
  changed_when: false
  when: users.ssh.fetch_key and users.ssh.deploy_key_user
  tags:
    - users-ssh

- name: Check fetched keys
  debug: msg="{{ users_ssh_keys.stdout }}"
  when: users.ssh.fetch_key and users.ssh.deploy_key_user
  tags:
    - users-ssh

- name: Deploy fetched keys to all hosts except same host on specific user
  authorized_key:
    user: "{{ users.ssh.deploy_key_user }}"
    key: "{{ hostvars[item]['users_ssh_keys']['stdout'] }}"
  with_items:
    - "{{ play_hosts }}"
  when: users.ssh.fetch_key and users.ssh.deploy_key_user and ansible_hostname != item
  tags:
    - users-ssh

- name: Add hosts to known hosts of each other
  known_hosts:
    path: "{{ users.ssh.known_hosts_path }}"
    name: "{{ item }}"
    key: "{{ item }} {{ hostvars[item]['users_ssh_keys']['stdout'] }}"
    state: present
  with_items:
    - "{{ play_hosts }}"
  when: users.ssh.known_hosts_path and users.ssh.fetch_key and users.ssh.deploy_key_user and ansible_hostname != item
  tags:
    - users-ssh
