---

- name: Add/remove users
  user:
    name: "{{ item.key }}"
    createhome: "{{ item.value.createhome|default(True) }}"
    shell: "{{ item.value.shell|default('/bin/bash') }}"
    generate_ssh_key: "{{ item.value.generate_ssh_key|default(True) }}"
    state: "{{ item.value.present|default('present') }}"
    password: "{{ item.value.password|default('') }}"
    update_password: "{{ item.value.update_password|default('always') }}"
    groups: "{{ item.value.groups|default(item.key) }}"
  with_dict: "{{ users }}"

- name: Remove user accounts from passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
    state: absent
    validate: 'visudo -cf %s'
  with_dict: "{{ users }}"
  when: item.value.sudoers_passwordless is not defined or not item.value.sudoers_passwordless

- name: Add user accounts to passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
  with_dict: "{{ users }}"
  when: item.value.sudoers_passwordless is defined and item.value.sudoers_passwordless
